# fly.toml file generated for book-club-bot on 2022-12-03T22:58:42-05:00

app = "book-club-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./Dockerfile.api"

[env]
  RACK_ENV="production"
  RAILS_ENV="production"
  RAILS_LOG_TO_STDOUT="ENABLE"
  RAILS_SERVE_STATIC_FILES="enabled"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
